version: "3.8"
services:
  llm_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_service
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD_FILE=/run/secrets/postgres_secrets
    secrets:
      - postgres_secrets
    networks:
      - llm_network
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--log-level"
      - "info"
      - "--reload" # Remove in production
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    container_name: qwen_backend
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull qwen3:0.6b &&
        tail -f /dev/null
      "
    networks:
      - llm_network

  postgres:
    image: docker.io/library/postgres:17.5-alpine
    container_name: lantern_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_secrets
      #- POSTGRES_PASSWORD=mysecretpassword
    secrets:
      - postgres_secrets
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - llm_network

networks:
  llm_network:
    driver: bridge

volumes:
  ollama_data:
  postgres_data:

secrets:
  postgres_secrets:
    file: ./secrets/postgres_secrets.txt
